logging:
  level:
    org:
      springframework:
        web: TRACE
      hibernate: ERROR
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}
  servlet:
    context-path: /desafioiterative-api
rick-and-morty:
  url: ${RICK_URL:https://rickandmortyapi.com/api/}
retry:
  max-attempt: 10
  interval: 3000
